apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'com.mytracker.finance.widgetbridge'
version = '1.0.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useExpoPublishing()

android {
  namespace "com.mytracker.finance.widgetbridge"
  defaultConfig {
    versionCode 1
    versionName "1.0.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation "androidx.security:security-crypto:1.1.0-alpha06"
}
